import { StatDefinition } from 'src/app/core/models/stat-definitions.model';

export const overallStatDefinitions: StatDefinition[] = [
  { label: 'STATS_LABEL.GAMES', key: 'totalGames', id: 'totalGames' },
  {
    label: 'STATS_LABEL.PERFECT_GAMES',
    key: 'perfectGameCount',
    id: 'perfectGameCount',
    toolTip: 'STATS_TOOLTIP.PERFECT_GAMES',
    prevKey: 'perfectGameCount',
  },
  {
    label: 'STATS_LABEL.CLEAN_GAMES',
    key: 'cleanGameCount',
    id: 'cleanGameCount',
    toolTip: 'STATS_TOOLTIP.CLEAN_GAMES',
    prevKey: 'cleanGameCount',
  },
  {
    label: 'STATS_LABEL.CLEAN_GAME_PERCENTAGE',
    key: 'cleanGamePercentage',
    id: 'cleanGamePercentage',
    isPercentage: true,
    toolTip: 'STATS_TOOLTIP.CLEAN_GAME_PERCENTAGE',
    prevKey: 'cleanGamePercentage',
  },
  { label: 'STATS_LABEL.AVERAGE', key: 'averageScore', id: 'averageScore', prevKey: 'averageScore' },
  { label: 'STATS_LABEL.HIGH_GAME', key: 'highGame', id: 'highGame' },
  { label: 'STATS_LABEL.TOTAL_PINS', key: 'totalPins', id: 'totalPins' },
  { label: 'STATS_LABEL.FIRST_BALL_AVERAGE', key: 'averageFirstCount', id: 'averageFirstCount', prevKey: 'averageFirstCount' },
  {
    label: 'STATS_LABEL.MARK_PERCENTAGE',
    key: 'markPercentage',
    id: 'markPercentage',
    isPercentage: true,
    toolTip: 'STATS_TOOLTIP.MARK_PERCENTAGE',
    prevKey: 'markPercentage',
  },
  {
    label: 'STATS_LABEL.STRIKE_PERCENTAGE',
    key: 'strikePercentage',
    id: 'strikePercentage',
    isPercentage: true,
    toolTip: 'STATS_TOOLTIP.STRIKE_PERCENTAGE',
    prevKey: 'strikePercentage',
  },
  {
    label: 'STATS_LABEL.SPARE_PERCENTAGE',
    key: 'overallSpareRate',
    id: 'sparePercentage',
    isPercentage: true,
    toolTip: 'STATS_TOOLTIP.SPARE_PERCENTAGE',
    prevKey: 'overallSpareRate',
  },
  {
    label: 'STATS_LABEL.OPEN_PERCENTAGE',
    key: 'overallMissedRate',
    id: 'openPercentage',
    isPercentage: true,
    toolTip: 'STATS_TOOLTIP.OPEN_PERCENTAGE',
    prevKey: 'overallMissedRate',
  },
];

export const specialStatDefinitions: StatDefinition[] = [
  {
    label: 'STATS_LABEL.DUTCH_200S',
    key: 'dutch200Count',
    id: 'dutch200Count',
    toolTip: 'STATS_TOOLTIP.DUTCH_200S',
  },
  {
    label: 'STATS_LABEL.VARIPAPA_300S',
    key: 'varipapa300Count',
    id: 'varipapa300Count',
    toolTip: 'STATS_TOOLTIP.VARIPAPA_300S',
  },
  {
    label: 'STATS_LABEL.FULL_SPARE_GAMES',
    key: 'allSparesGameCount',
    id: 'allSparesGameCount',
    toolTip: 'STATS_TOOLTIP.FULL_SPARE_GAMES',
  },
];

export const playFrequencyStatDefinitions: StatDefinition[] = [
  {
    label: 'STATS_LABEL.AVG_GAMES_PER_WEEK',
    key: 'averageGamesPerWeek',
    id: 'averageGamesPerWeek',
  },
  {
    label: 'STATS_LABEL.AVG_GAMES_PER_MONTH',
    key: 'averageGamesPerMonth',
    id: 'averageGamesPerMonth',
  },
  {
    label: 'STATS_LABEL.AVG_SESSIONS_PER_WEEK',
    key: 'averageSessionsPerWeek',
    id: 'averageSessionsPerWeek',
    toolTip: 'STATS_TOOLTIP.AVG_SESSIONS_PER_WEEK',
  },
  {
    label: 'STATS_LABEL.AVG_SESSIONS_PER_MONTH',
    key: 'averageSessionsPerMonth',
    id: 'averageSessionsPerMonth',
    toolTip: 'STATS_TOOLTIP.AVG_SESSIONS_PER_MONTH',
  },
  {
    label: 'STATS_LABEL.AVG_GAMES_PER_SESSION',
    key: 'averageGamesPerSession',
    id: 'averageGamesPerSession',
    toolTip: 'STATS_TOOLTIP.AVG_GAMES_PER_SESSION',
  },
];

export const seriesStatDefinitions: StatDefinition[] = [
  { label: 'STATS_LABEL.AVG_3_SERIES', key: 'average3SeriesScore', id: 'average3SeriesScore', prevKey: 'average3SeriesScore' },
  { label: 'STATS_LABEL.HIGH_3_SERIES', key: 'high3Series', id: 'high3Series' },
  { label: 'STATS_LABEL.AVG_4_SERIES', key: 'average4SeriesScore', id: 'average4SeriesScore', prevKey: 'average4SeriesScore' },
  { label: 'STATS_LABEL.HIGH_4_SERIES', key: 'high4Series', id: 'high4Series' },
  { label: 'STATS_LABEL.AVG_5_SERIES', key: 'average5SeriesScore', id: 'average5SeriesScore', prevKey: 'average5SeriesScore' },
  { label: 'STATS_LABEL.HIGH_5_SERIES', key: 'high5Series', id: 'high5Series' },
  { label: 'STATS_LABEL.AVG_6_SERIES', key: 'average6SeriesScore', id: 'average6SeriesScore', prevKey: 'average6SeriesScore' },
  { label: 'STATS_LABEL.HIGH_6_SERIES', key: 'high6Series', id: 'high6Series' },
];

export const leagueStatDefinitions: StatDefinition[] = [
  { label: 'STATS_LABEL.GAMES', key: 'totalGames', id: 'league-totalGames' },
  {
    label: 'STATS_LABEL.PERFECT_GAMES',
    key: 'perfectGameCount',
    id: 'league-perfectGameCount',
    toolTip: 'STATS_TOOLTIP.PERFECT_GAMES',
  },
  {
    label: 'STATS_LABEL.CLEAN_GAMES',
    key: 'cleanGameCount',
    id: 'league-cleanGameCount',
    toolTip: 'STATS_TOOLTIP.CLEAN_GAMES',
  },
  {
    label: 'STATS_LABEL.CLEAN_GAME_PERCENTAGE',
    key: 'cleanGamePercentage',
    id: 'league-cleanGamePercentage',
    isPercentage: true,
    toolTip: 'STATS_TOOLTIP.CLEAN_GAME_PERCENTAGE',
    prevKey: 'cleanGamePercentage',
  },
  { label: 'STATS_LABEL.AVERAGE', key: 'averageScore', id: 'league-averageScore', prevKey: 'averageScore' },
  { label: 'STATS_LABEL.HIGH_GAME', key: 'highGame', id: 'league-highGame' },
  { label: 'STATS_LABEL.TOTAL_PINS', key: 'totalPins', id: 'league-totalPins' },
  { label: 'STATS_LABEL.FIRST_BALL_AVERAGE', key: 'averageFirstCount', id: 'league-averageFirstCount', prevKey: 'averageFirstCount' },
  { label: 'STATS_LABEL.TOTAL_STRIKES', key: 'totalStrikes', id: 'league-totalStrikes' },
  { label: 'STATS_LABEL.STRIKES_PER_GAME', key: 'averageStrikesPerGame', id: 'league-averageStrikesPerGame', prevKey: 'averageStrikesPerGame' },
  { label: 'STATS_LABEL.MARK_PERCENTAGE', key: 'markPercentage', id: 'league-markPercentage', isPercentage: true, prevKey: 'markPercentage' },
  {
    label: 'STATS_LABEL.STRIKE_PERCENTAGE',
    key: 'strikePercentage',
    id: 'league-strikePercentage',
    isPercentage: true,
    toolTip: 'STATS_TOOLTIP.STRIKE_PERCENTAGE',
    prevKey: 'strikePercentage',
  },
  { label: 'STATS_LABEL.TOTAL_SPARES', key: 'totalSpares', id: 'league-totalSpares' },
  { label: 'STATS_LABEL.SPARES_PER_GAME', key: 'averageSparesPerGame', id: 'league-averageSparesPerGame', prevKey: 'averageSparesPerGame' },
  {
    label: 'STATS_LABEL.SPARE_PERCENTAGE',
    key: 'overallSpareRate',
    id: 'league-sparePercentage',
    isPercentage: true,
    toolTip: 'STATS_TOOLTIP.SPARE_PERCENTAGE',
    prevKey: 'overallSpareRate',
  },
  { label: 'STATS_LABEL.TOTAL_OPENS', key: 'totalSparesMissed', id: 'totalSparesMissed' },
  { label: 'STATS_LABEL.OPENS_PER_GAME', key: 'averageOpensPerGame', id: 'league-averageOpensPerGame', prevKey: 'averageOpensPerGame' },
  {
    label: 'STATS_LABEL.OPEN_PERCENTAGE',
    key: 'overallMissedRate',
    id: 'league-openPercentage',
    isPercentage: true,
    toolTip: 'STATS_TOOLTIP.OPEN_PERCENTAGE',
    prevKey: 'overallMissedRate',
  },
];

export const throwStatDefinitions: StatDefinition[] = [
  { label: 'STATS_LABEL.TOTAL_STRIKES', key: 'totalStrikes', id: 'totalStrikes' },
  { label: 'STATS_LABEL.STRIKES_PER_GAME', key: 'averageStrikesPerGame', id: 'averageStrikesPerGame', prevKey: 'averageStrikesPerGame' },
  { label: 'STATS_LABEL.TOTAL_SPARES', key: 'totalSpares', id: 'totalSpares' },
  { label: 'STATS_LABEL.SPARES_PER_GAME', key: 'averageSparesPerGame', id: 'averageSparesPerGame', prevKey: 'averageSparesPerGame' },
  { label: 'STATS_LABEL.TOTAL_OPENS', key: 'totalSparesMissed', id: 'totalSparesMissed' },
  { label: 'STATS_LABEL.OPENS_PER_GAME', key: 'averageOpensPerGame', id: 'averageOpensPerGame', prevKey: 'averageOpensPerGame' },
  {
    label: 'STATS_LABEL.LONGEST_OPEN_STREAK',
    key: 'longestOpenStreak',
    id: 'longestOpenStreak',
    toolTip: 'STATS_TOOLTIP.LONGEST_OPEN_STREAK',
  },
];

export const strikeStatDefinitions: StatDefinition[] = [
  { label: 'Turkeys', key: 'turkeyCount', id: 'turkeyCount', toolTip: 'STATS_TOOLTIP.TURKEYS' },
  { label: '4-baggers', key: 'bagger4Count', id: 'fourBaggerCount', toolTip: 'STATS_TOOLTIP.BAGGER_4' },
  { label: '5-baggers', key: 'bagger5Count', id: 'bagger5Count', toolTip: 'STATS_TOOLTIP.BAGGER_5' },
  { label: '6-baggers', key: 'bagger6Count', id: 'bagger6Count', toolTip: 'STATS_TOOLTIP.BAGGER_6' },
  { label: '7-baggers', key: 'bagger7Count', id: 'bagger7Count', toolTip: 'STATS_TOOLTIP.BAGGER_7' },
  { label: '8-baggers', key: 'bagger8Count', id: 'bagger8Count', toolTip: 'STATS_TOOLTIP.BAGGER_8' },
  { label: '9-baggers', key: 'bagger9Count', id: 'bagger9Count', toolTip: 'STATS_TOOLTIP.BAGGER_9' },
  { label: '10-baggers', key: 'bagger10Count', id: 'bagger10Count', toolTip: 'STATS_TOOLTIP.BAGGER_10' },
  { label: '11-baggers', key: 'bagger11Count', id: 'bagger11Count', toolTip: 'STATS_TOOLTIP.BAGGER_11' },
  {
    label: 'STATS_LABEL.LONGEST_STRIKE_STREAK',
    key: 'longestStrikeStreak',
    id: 'longestStrikeStreak',
    toolTip: 'STATS_TOOLTIP.LONGEST_STRIKE_STREAK',
  },
  {
    label: 'STATS_LABEL.STRIKE_TO_STRIKE_PCT',
    key: 'strikeToStrikePercentage',
    prevKey: 'strikeToStrikePercentage',
    id: 'strikeToStrikePercentage',
    isPercentage: true,
    toolTip: 'STATS_TOOLTIP.STRIKE_TO_STRIKE_PCT',
  },
  {
    label: 'STATS_LABEL.STRIKEOUTS',
    key: 'strikeoutCount',
    id: 'strikeoutCount',
    toolTip: 'STATS_TOOLTIP.STRIKEOUTS',
  },
];

export const spareStatDefinitions: StatDefinition[] = [
  {
    label: 'STATS_LABEL.SINGLE_PIN_SPARES',
    key: 'singlePinSpares',
    id: 'singlePinSpares',
    secondaryKey: 'singlePinSpareOpportunities',
    toolTip: 'STATS_TOOLTIP.SINGLE_PIN_SPARES',
  },
  {
    label: 'STATS_LABEL.MULTI_PIN_SPARES',
    key: 'multiPinSpares',
    id: 'multiPinSpares',
    secondaryKey: 'multiPinSpareOpportunities',
    toolTip: 'STATS_TOOLTIP.MULTI_PIN_SPARES',
  },
  {
    label: 'STATS_LABEL.SINGLE_PIN_SPARE_PCT',
    key: 'singlePinSparePercentage',

    id: 'singlePinSparePercentage',
    isPercentage: true,
    prevKey: 'singlePinSparePercentage',
  },
  {
    label: 'STATS_LABEL.MULTI_PIN_SPARE_PCT',
    key: 'multiPinSparePercentage',
    id: 'multiPinSparePercentage',
    isPercentage: true,
    prevKey: 'multiPinSparePercentage',
  },
];

export const pinStatDefinitions: StatDefinition[] = [
  {
    label: 'STATS_LABEL.POCKET_HITS',
    key: 'pocketHits',
    id: 'pocketHits',
    secondaryKey: 'totalFirstBalls',
    toolTip: 'STATS_TOOLTIP.POCKET_HITS',
  },
  {
    label: 'STATS_LABEL.POCKET_HIT_PCT',
    key: 'pocketHitPercentage',
    id: 'pocketHitPercentage',
    isPercentage: true,
    prevKey: 'pocketHitPercentage',
    toolTip: 'STATS_TOOLTIP.POCKET_HIT_PCT',
  },
  {
    label: 'STATS_LABEL.NON_SPLIT_SPARES',
    key: 'nonSplitSpares',
    id: 'nonSplitSpares',
    secondaryKey: 'nonSplitSpareOpportunities',
  },
  {
    label: 'STATS_LABEL.NON_SPLIT_SPARE_PCT',
    key: 'nonSplitSparePercentage',
    id: 'nonSplitSparePercentage',
    isPercentage: true,
    prevKey: 'nonSplitSparePercentage',
  },
  {
    label: 'STATS_LABEL.SPLIT_CONVERSIONS',
    key: 'splits',
    id: 'splits',
    secondaryKey: 'splitOpportunities',
  },
  {
    label: 'STATS_LABEL.SPLIT_CONVERSION_PCT',
    key: 'splitConversionPercentage',
    id: 'splitConversionPercentage',
    isPercentage: true,
    prevKey: 'splitConversionPercentage',
  },
  {
    label: 'STATS_LABEL.MAKEABLE_SPLIT_CONVERSIONS',
    key: 'makeableSplits',
    id: 'makeableSplits',
    secondaryKey: 'makeableSplitOpportunities',
    toolTip: 'STATS_TOOLTIP.MAKEABLE_SPLIT_CONVERSIONS',
  },
  {
    label: 'STATS_LABEL.MAKEABLE_SPLIT_PCT',
    key: 'makeableSplitPercentage',
    prevKey: 'makeableSplitPercentage',
    id: 'makeableSplitPercentage',
    isPercentage: true,
    toolTip: 'STATS_TOOLTIP.MAKEABLE_SPLIT_PCT',
  },
];

export const sessionStatDefinitions: StatDefinition[] = [
  { label: 'STATS_LABEL.GAMES', key: 'totalGames', id: 'sessionTotalGames' },
  {
    label: 'STATS_LABEL.PERFECT_GAMES',
    key: 'perfectGameCount',
    id: 'sessionPerfectGameCount',
    toolTip: 'STATS_TOOLTIP.PERFECT_GAMES',
  },
  {
    label: 'STATS_LABEL.CLEAN_GAMES',
    key: 'cleanGameCount',
    id: 'sessionCleanGameCount',
    toolTip: 'STATS_TOOLTIP.CLEAN_GAMES',
  },
  {
    label: 'STATS_LABEL.CLEAN_GAME_PERCENTAGE',
    key: 'cleanGamePercentage',
    id: 'sessionCleanGamePercentage',
    isPercentage: true,
    toolTip: 'STATS_TOOLTIP.CLEAN_GAME_PERCENTAGE',
    prevKey: 'cleanGamePercentage',
  },
  { label: 'STATS_LABEL.AVERAGE', key: 'averageScore', id: 'sessionAverage', prevKey: 'averageScore' },
  { label: 'STATS_LABEL.HIGH_GAME', key: 'highGame', id: 'sessionHighGame' },
  { label: 'STATS_LABEL.LOW_GAME', key: 'lowGame', id: 'sessionLowGame' },
  { label: 'STATS_LABEL.TOTAL_PINS', key: 'totalPins', id: 'sessionTotalPins' },
  { label: 'STATS_LABEL.FIRST_BALL_AVERAGE', key: 'averageFirstCount', id: 'sessionAverageFirstCount', prevKey: 'averageFirstCount' },
  { label: 'STATS_LABEL.TOTAL_STRIKES', key: 'totalStrikes', id: 'sessionTotalStrikes' },
  { label: 'STATS_LABEL.STRIKES_PER_GAME', key: 'averageStrikesPerGame', id: 'sessionAverageStrikesPerGame', prevKey: 'averageStrikesPerGame' },
  {
    label: 'STATS_LABEL.STRIKE_PERCENTAGE',
    key: 'strikePercentage',
    id: 'sessionStrikePercentage',
    isPercentage: true,
    toolTip: 'STATS_TOOLTIP.STRIKE_PERCENTAGE',
    prevKey: 'strikePercentage',
  },
  { label: 'STATS_LABEL.TOTAL_SPARES', key: 'totalSpares', id: 'sessionTotalSpares' },
  { label: 'STATS_LABEL.SPARES_PER_GAME', key: 'averageSparesPerGame', id: 'sessionAverageSparesPerGame', prevKey: 'averageSparesPerGame' },
  {
    label: 'STATS_LABEL.SPARE_PERCENTAGE',
    key: 'overallSpareRate',
    id: 'sessionSparePercentage',
    isPercentage: true,
    toolTip: 'STATS_TOOLTIP.SPARE_PERCENTAGE',
    prevKey: 'overallSpareRate',
  },
  { label: 'STATS_LABEL.TOTAL_OPENS', key: 'totalSparesMissed', id: 'sessionTotalSparesMissed' },
  { label: 'STATS_LABEL.OPENS_PER_GAME', key: 'averageOpensPerGame', id: 'sessionAverageOpensPerGame', prevKey: 'averageOpensPerGame' },
  {
    label: 'STATS_LABEL.OPEN_PERCENTAGE',
    key: 'overallMissedRate',
    id: 'sessionOpenPercentage',
    isPercentage: true,
    toolTip: 'STATS_TOOLTIP.OPEN_PERCENTAGE',
    prevKey: 'overallMissedRate',
  },
];
